language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - yarn install # npm ci
script:
  - yarn docs:build && yarn cname # npm run docs:build
after_script:
  - git push -f git@github.com:pxinc/pxinc.github.io.git master
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/.vuepress/dist
    github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
    keep_history: true
    on:
      branch: master